---
# This GitHub Actions workflow calculates the code coverage of the extension and uploads it to coveralls.io.
name: Code coverage
on:
  push:
    branches:
      - main
  pull_request:
permissions:
  contents: read
jobs:
  # @todo Rethink the whole implementation. It's possible to consider creating the part coverage logs directly
  #       for all unit, unitRandom and functional tests in the `ci.yml` workflow and using this only to merge
  #       and upload it. That would avoid reexecuting only for a subset of matrix run here again.
  #       In general there are two different approaches when doing the above mentioned considerations:
  #
  #       * Use job artifacts to get all of the `Build/coverage/*.pcov` files and merge it using the pcov tool
  #       * Use parallel partly upload in ci.yaml unit, unitRandom, functional test runs and use this to finish
  #         the parallel execution. See: https://github.com/coverallsapp/github-action#complete-parallel-job-example
  code-coverage:
    name: Calculate code coverage
    permissions:
      actions: write
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Show the Composer version
        run: ./Build/Scripts/runTests.sh -s composer -- --version
      - name: Show the Composer configuration
        run:  ./Build/Scripts/runTests.sh -s composer config --global --list
      - name: Install composer dependencies
        run: |
          ./Build/Scripts/runTests.sh -p ${{ matrix.php-version }} -t ${{matrix.typo3-version}} -s composerUpdate${{matrix.composer-dependencies}}
      # @todo Consider to execute all unit tests with coverage and using job artifacts to merge them in one place
      #       instead of executing only one run here with coverage. Could also be combined directly uploading the
      #       parallel executions as partly upload and using this workflow only to make the final webhook call.
      - name: Run unit tests with coverage
        run: |
          ./Build/Scripts/runTests.sh -p ${{ matrix.php-version }} -s unit -m
      # @todo Consider to execute all functional tests with coverage and using job artifacts to merge them in one place
      #       instead of executing only one run here with coverage. Could also be combined directly uploading the
      #       parallel executions as partly upload and using this workflow only to make the final webhook call.
      - name: Run functional tests with coverage
        run: |
          ./Build/Scripts/runTests.sh -p ${{ matrix.php-version }} -s functional -m
      - name: Show generated coverage files
        run: |
          ls -lahR Build/coverage/
      # @todo
      - name: Merge coverage results
        run: |
          ./Build/Scripts/runTests.sh -p ${{ matrix.php-version }} -s coverageMerge
      - name: Show combined coverage files
        run: "ls -lahR Build/logs/"
      - name: Upload coverage results to Coveralls
        uses: coverallsapp/github-action@v2
        env:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          file: Build/logs/clover.xml
    strategy:
      fail-fast: false
      matrix:
        include:
          - typo3-version: "12.4"
            php-version: "8.3"
            composer-dependencies: Max
